import PushNotification from 'react-native-push-notification';

export default class NotifService {

  constructor(onRegister) {
    this.configure(onRegister);
    this.lastId = 0;
  }

  configure(onRegister) {
    PushNotification.configure({
      onRegister: onRegister, //this._onRegister.bind(this),
      senderID: '737755359918',
      popInitialNotification: true,
      requestPermissions: true
    });
  }

  localNotif(type) {
    if (type === 'Bienvenida') {
      PushNotification.localNotificationSchedule({
        date: new Date(Date.now() + (5 * 1000)),
        /* Android Only Properties */
        id: ''+this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        //ticker: "My Notification Ticker", // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "Consultá tu situación fiscal, evacuá todas tus dudas sobre tu Monotributo, y Facturá de manera sencilla y GRATIS!", // (optional) default: "message" prop
        //subText: "This is a subText", // (optional) default: none
        color: "blue", // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification

        /* iOS and Android properties */
        title: "Hola, Soy Bill!", // (optional)
        message: "Y voy a ser tu contador online...", // (required)
      });
    }
  }

  
  checkPermission(cbk) {
    return PushNotification.checkPermissions(cbk);
  }

  cancelNotif() {
    PushNotification.cancelLocalNotifications({id: ''+this.lastId});
  }

  cancelAll() {
    PushNotification.cancelAllLocalNotifications();
  }
}